#!/bin/bash
set -e

cat .io.livecode.ch/header.txt $1 .io.livecode.ch/footer.txt >out.scm
if [ -s $2 ]
then
    vicare -f init.scm -f $2 --script out.scm
else
    vicare -f init.scm --script out.scm
fi
